version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - app-data:/app/data
    environment:
      - NODE_ENV=development
      - DB_FILE=/app/data/timetable.sqlite3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app-data:
